sudo: required
git:
  depth: 1
common_sources: &1
- ubuntu-toolchain-r-test
language: cpp
matrix:
  include:
  - os: osx
    osx_image: xcode10.3
    env:
      - MATRIX_EVAL="CC=clang && CXX=clang++ && PYTHON=python3.7"
  - os: linux
    dist: xenial
    addons:
      apt:
        sources: *1
        packages:
        - g++-5
    env:
    - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && PYTHON=python3.6"
  - os: linux
    dist: xenial
    addons:
      apt:
        sources: *1
        packages:
        - g++-5
    env:
    - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && PYTHON=python3.7"

before_install:
- eval "${MATRIX_EVAL}"
- echo $CXX
- echo $PYTHON

script:
- $PYTHON -m pip install taichi-nightly && $PYTHON -m taichi test


