#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.0.{build}-{branch}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017
clone_folder: C:\taichi

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: x64
configuration: Release


environment:
  matrix:
    - PYTHON: C:\Python36-x64\python.exe
    - PYTHON: C:\Python37-x64\python.exe


build_script:
  - "%PYTHON% -m pip install taichi-nightly"
  - "%PYTHON% -m taichi test"

